/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface EIP712BaseContract
  extends Truffle.Contract<EIP712BaseInstance> {
  "new"(meta?: Truffle.TransactionDetails): Promise<EIP712BaseInstance>;
}

type AllEvents = never;

export interface EIP712BaseInstance extends Truffle.ContractInstance {
  ERC712_VERSION(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getDomainSeperator(txDetails?: Truffle.TransactionDetails): Promise<string>;

  getChainId(txDetails?: Truffle.TransactionDetails): Promise<BN>;

  methods: {
    ERC712_VERSION(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getDomainSeperator(txDetails?: Truffle.TransactionDetails): Promise<string>;

    getChainId(txDetails?: Truffle.TransactionDetails): Promise<BN>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
