/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ERC165Contract } from "./ERC165";
import { ERC2309Contract } from "./ERC2309";
import { ERC721Contract } from "./ERC721";
import { ERC721EnumerableContract } from "./ERC721Enumerable";
import { ERC721URIStorageContract } from "./ERC721URIStorage";
import { IERC165Contract } from "./IERC165";
import { IERC721Contract } from "./IERC721";
import { IERC721EnumerableContract } from "./IERC721Enumerable";
import { IERC721MetadataContract } from "./IERC721Metadata";
import { IERC721ReceiverContract } from "./IERC721Receiver";
import { MigrationsContract } from "./Migrations";
import { OpenSeaPolygonERC721Contract } from "./OpenSeaPolygonERC721";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ERC165"): ERC165Contract;
      require(name: "ERC2309"): ERC2309Contract;
      require(name: "ERC721"): ERC721Contract;
      require(name: "ERC721Enumerable"): ERC721EnumerableContract;
      require(name: "ERC721URIStorage"): ERC721URIStorageContract;
      require(name: "IERC165"): IERC165Contract;
      require(name: "IERC721"): IERC721Contract;
      require(name: "IERC721Enumerable"): IERC721EnumerableContract;
      require(name: "IERC721Metadata"): IERC721MetadataContract;
      require(name: "IERC721Receiver"): IERC721ReceiverContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "OpenSeaPolygonERC721"): OpenSeaPolygonERC721Contract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { ERC165Contract, ERC165Instance } from "./ERC165";
export { ERC2309Contract, ERC2309Instance } from "./ERC2309";
export { ERC721Contract, ERC721Instance } from "./ERC721";
export {
  ERC721EnumerableContract,
  ERC721EnumerableInstance,
} from "./ERC721Enumerable";
export {
  ERC721URIStorageContract,
  ERC721URIStorageInstance,
} from "./ERC721URIStorage";
export { IERC165Contract, IERC165Instance } from "./IERC165";
export { IERC721Contract, IERC721Instance } from "./IERC721";
export {
  IERC721EnumerableContract,
  IERC721EnumerableInstance,
} from "./IERC721Enumerable";
export {
  IERC721MetadataContract,
  IERC721MetadataInstance,
} from "./IERC721Metadata";
export {
  IERC721ReceiverContract,
  IERC721ReceiverInstance,
} from "./IERC721Receiver";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export {
  OpenSeaPolygonERC721Contract,
  OpenSeaPolygonERC721Instance,
} from "./OpenSeaPolygonERC721";
export { OwnableContract, OwnableInstance } from "./Ownable";
